services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epay-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - app_data:/var/www/html/data
    user: "1000:1000"
    # 应用容器不需要数据库环境变量，通过Web安装程序配置
    depends_on:
      - mysql
    networks:
      - epay-network

  mysql:
    image: mysql:8.0
    container_name: epay-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-epay}
      MYSQL_USER: ${MYSQL_USER:-epay_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-epay_pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    networks:
      - epay-network

  nginx:
    image: nginx:alpine
    container_name: epay-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - epay-network

volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local

networks:
  epay-network:
    driver: bridge